---
title: "House Prices"
author: "Asger Rasmussen"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(fable)
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(zoo)
library(ggthemes)
library(tsibble)
library(feasts)
theme_set(theme_fivethirtyeight())

```

Load in the data & Clean the data

```{r}

House_Prices_raw <- read_excel("Data/House Price Kommune Quarter.xlsx")

House_Prices <- House_Prices_raw %>% 
  filter(!row_number() %in% c(1)) %>% 
  row_to_names(., 1) %>% 
  clean_names() %>% 
  as_tibble() %>% 
  rename(Date = na,
         Category = na_2,
         Type = na_3,
         Capital = capital_region,
         Zealand = region_zealand,
         "Central Denmark" = central_denmark_region,
         "Sourth Denmark" = region_of_southern_denmark,
         "North Jutland" = region_of_north_jutland
         ) %>% 
  mutate(Date = as.Date(as.yearmon(Date, "%YM%m"), frac = 1)) %>% 
  select(-Category, -Type) %>% 
  pivot_longer(
    cols = Capital:"North Jutland",
    names_to = "Region",
    values_to = "Price"
  ) %>% 
  mutate(Price = as.integer(Price)) %>% 
  as_tsibble(Date, key = Region)

House_Prices_MM <- House_Prices %>% 
  as.tibble() |>
  group_by(Date) |> 
  summarise(mean = mean(Price),
            median = median(Price)) |>
  mutate(Month = yearmonth(Date)) |>
  as_tsibble(index = Month) |> 
  select(-Date)

```

Initial visualising of the data

```{r}

colors <- c("Mean" = "royalblue", "Median" = "darkred")

House_Prices %>% 
  as.tibble() |>
  group_by(Date) |> 
  summarise(mean = mean(Price),
            median = median(Price)) |> 
  ggplot(aes(x = Date)) +
  geom_line(aes(y = mean, color = "Mean")) +
  geom_line(aes(y = median, color = "Median")) +
  labs(
    title = "Mean and Median house over time",
    subtitle = "Unit in DKK per m2",
    x = "Date",
    color = "Price Type"
  ) +
  scale_color_manual(values = c("Mean" = "royalblue", "Median" = "darkred"))
  
  
House_Prices %>% 
  autoplot(log(Price)) +
  labs(
    title = "Property log prices by Region",
    subtitle = "Unit in log DKK per m2",
    x = "Date"
  )

```

Let us run some simple models

```{r}

House_Prices_MM |> 
  filter(Month < yearmonth("2020 Jan")) %>% 
  model(
  ets = ETS(mean),
  arima = ARIMA(mean),
  lm = TSLM(mean ~ trend() + season())
  ) |>
  forecast(h = "10 months") |> 
  accuracy(House_Prices_MM)

## ARIMA seems best

fit <- House_Prices_MM |> 
  model(
  arima = ARIMA(mean)
  )

```

Arima Seems best with a RMSE of 339.1821, so let us run a perfect model with arima

```{r}

forecast <- fit |> 
  forecast(h = "6 month")

House_Prices_MM |> 
  ggplot(aes(x = Month)) +
  geom_point(aes(y = mean)) +
  geom_point(aes(x = Month, y = forecast$.mean))


```




